
# Product adverts menu items definition
entity.product_adverts.collection:
  title: 'Product adverts'
  route_name: entity.product_adverts.collection
  description: 'Manage product adverts.'
  parent: commerce.admin_commerce
  weight: 100
