<?php

/**
 * @file
 * Contains product_adverts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function product_adverts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the product_adverts module.
    case 'help.page.product_adverts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function product_adverts_theme($existing, $type, $theme, $path) {
  return [
    'adverts_swiper' => [
      'variables' => [
        'adverts' => []
      ],
    ],
    'adverts_banner' => [
      'variables' => [
        'advert' => NULL,
        'show_new_tag' => false,
        'text_color' => '#000000'
      ]
    ],
    'adverts_latest_products' => [
      'variables' => [
        'products' => []
      ]
    ],
    'adverts_top_products' => [
      'variables' => [
        'block_title' => null,
        'categories' => [],
        'products' => [],
        'more' => null
      ]
    ]
  ];
}
