name: 'Product Adverts'
type: module
description: 'Provides commerce product adverts.'
core: 8.x
package: Custom
dependencies:
  - commerce_product
  - product_adverts
  - rest
  - serialization
  - views
