<?php

/**
 * @file
 * Contains product_adverts.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function product_adverts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the product_adverts module.
    case 'help.page.product_adverts':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
